version: "3.7"

services:
  device-monitoring-api-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRESQL_PASSWORD=Ii13a2019
      - POSTGRESQL_DATABASE=device_monitoring
  device-monitoring-api-pgadmin:
    image: dpage/pgadmin4
    ports:
      - 82:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=devicemonitoring@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Ii13a2019
